spring:
  application:
    name: toolsleasing
  datasource:
    url: jdbc:postgresql://localhost:5432/JavaDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    properties:
      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation=true
#        dialect: org.hibernate.dialect.PostgreSQLDialect